name: Publish

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["16.x"]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          registry-url: 'https://registry.npmjs.org'
          
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: git config --global user.email "simon.jutz@cytex.ch"
      - run: git config --global user.name "Simon Jutz"
      - run: npm i
      - run: npm run compile
      - run: npm run publish-package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
